# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagementsystemapp', '0005_auto_20180924_1627'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expenses',
            table='expenses',
        ),
    ]
