# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-25 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagementsystemapp', '0007_auto_20180924_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='user_dob',
        ),
    ]
